### ISSUE TITLE
Try to login using email as username and password I got login error with error code 151

### ISSUE THREAD

**Issue by zhengye1** [MahjongRepository/mahjong_soul_api#7] opened 2021-12-28 01:34 UTC
Try to use the API to generate some of the data from the tournament match (or call contest), but I got login error 
![image](https://user-images.githubusercontent.com/5428784/147518124-afb222ff-f7da-4d0c-9d1d-4bc697812173.png)

What can I do for that?

**Comment by Nihisil** [comment] 2021-12-28 03:18
The issue is that MS requires you to change the `client_version_string` value after each new version release, otherwise they don't allow you to login with the old version (151 error code about that).

It wasn't convenient, so I updated `example.py` to choose a new version automatically based on the server config. It looks like it is working, but can be broken again later with future updates of MS. I will keep an eye on it.

**Comment by Nihisil** [comment] 2021-12-28 03:20
Please check new released version https://pypi.org/project/ms-api/0.10.1/ and updated [example.py ](https://github.com/MahjongRepository/mahjong_soul_api/blob/master/example.py) and let me know if the issue was resolved

**Comment by zhengye1** [comment] 2021-12-30 22:54
That resolved. However I try to pull the record and I got 0 record found...

**Comment by Nihisil** [comment] 2021-12-31 01:41
Do you have played games on your account? The script shows me:
```
2021-12-31 09:40:37 INFO: Connection was established
2021-12-31 09:40:37 INFO: Login with username and password
2021-12-31 09:40:37 INFO: Loading game logs
2021-12-31 09:40:39 INFO: Found 30 records
```

**Comment by zhengye1** [comment] 2021-12-31 04:10
I created a new account and just play one game...

**Comment by Nihisil** [comment] 2021-12-31 07:17
With that I can't help, you need to investigate what is going on. This is a repository just for protobuf methods to interact with MS API. The `example.py` file is something where you can start, but deeper interaction with MS API is out of scope for this repository.

**Comment by zhengye1** [comment] 2021-12-31 07:18
OK, i try to dig out then, thank you

**Closed as completed by Nihisil** 2021-12-31 07:17 UTC
